name: Go

on:
  push:
    tags:
    - '*'
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: build
    strategy:
      matrix:
        go-arch: [amd64, arm64]
        go-os: [linux, darwin]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: env GOOS=${{ matrix.go-os }} GOARCH=${{ matrix.go-arch }} go build -o ./build/jbackup-${{ matrix.go-os }}-${{ matrix.go-arch }} .
  release:
    name: release
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: publish release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/*"
        token: ${{ secrets.GITHUB_TOKEN }}